task/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('taskapp.urls')),
]

taskapp/urls.py
from django.urls import path
from . import views


app_name = 'taskapp'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('login/', views.loginPage, name = 'login'),
    path('user/',views.userPage,name='user-page'),
    path('register/', views.registerPage, name = 'register'),
    path('logout/',views.logoutUser, name='logout'),
    path('createTask', views.createTask, name = 'createTask'),
    path('editTask/<int:pk>', views.editTask, name = 'editTask'),
    path('deleteTask/<int:pk>', views.deleteTask, name='deleteTask'),
    path('viewTask/<int:pk>', views.viewTask, name = 'viewTask'),
]

taskapp/models.py
from django.db import models
from django.utils import timezone

class Task(models.Model):
    name = models.CharField(max_length = 40)
    email = models.EmailField(max_length=100)
    title = models.CharField(max_length = 100)
    description = models.CharField(max_length = 400)
    link_id = models.AutoField(primary_key = True)
    datecreated = models.DateTimeField()
    datelastmodified = models.DateTimeField()

    def save(self, *args, **kwargs):
        if not self.link_id:
            self.datecreated = timezone.now()
        else:
            self.datecreated = self.getCreatedDate()
        self.datelastmodified = timezone.now()
        return super(Task, self).save(*args, **kwargs)

    def __str__(self):
        return self.title
    
    def getCreatedDate(self):
        return self.datecreated

class Comments(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    comment = models.CharField(max_length = 200)

    def __str__(self):
        return self.comment

taskapp/forms.py
from attr import field
from django import forms
from django.forms import (formset_factory, modelformset_factory)
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Task, Comments

class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ('name','email','title','description','link_id','datecreated','datelastmodified',)
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter Name of Person to whom this task is assigned'
            }),
            'email': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter the email of the Person'
            }),
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter the Title of the Task'
            }),
            'description': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter description of this task'
            }),
            'datecreated': forms.DateTimeInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter the Date when this Task created',
                'type':'date'
            }),
            'datelastmodified': forms.DateTimeInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter Last Modified date of the task',
                'type':'date'
            })
            
        }

class CommentsForm(forms.ModelForm):

    class Meta:
        model = Comments
        fields = ('task','comment',)
        task_list = Task.objects.all()
        widgets = {
            'task': forms.Select(attrs={
                'class': 'form-control',
                'placeholder': 'Enter the comments'
                },
                choices = task_list
            ),
            'comment': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter the comments'
            })
        }


class CreateUserForm(UserCreationForm):
    class Meta:
        model= User
        fields=['username','email','password1','password2']

taskapp/views.py
from task import settings
from django.shortcuts import render,redirect
from django.contrib.auth.models import Group
from django.contrib.auth.models import User
import task
from taskapp.decorators import admin_only, allowed_users, unauthenticated_user
from .forms import TaskForm, CommentsForm, CreateUserForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from taskapp.models import Task, Comments
from django.template.loader import render_to_string

from django.contrib.auth import authenticate, login, logout
# Create your views here.

@login_required(login_url='taskapp:login')
def index(request):
    tasklist = Task.objects.all()
    context = {'tasklist': tasklist}
    return render(request, 'taskapp/index.html', context)

@unauthenticated_user
def registerPage(request):
    form = CreateUserForm()
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user=form.save()
            username= form.cleaned_data.get('username')

            group = Group.objects.get(name='user')
            user.groups.add(group)

            messages.success(request, 'Account was Successfully created for '+ username)
            return redirect('taskapp:login')

    context ={'form':form}
    return render(request, 'taskapp/register.html', context)

def logoutUser(request):
    logout(request)
    return redirect('taskapp:login')

def userPage(request):
    context={}
    return render(request, 'taskapp/user.html', context)


@login_required(login_url='taskapp:login')
@allowed_users(allowed_roles=['admin'])
def createTask(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)

        useremail = request.POST.get('email')
        username = request.POST.get('name')
        taskTitle = request.POST.get('title')
        taskDescription = request.POST.get('description')
        
        send_mail(subject='New Task Assigned',
        message =f'NEW EMAIL FROM "COMPANY NAME".\n\nHello {username},\nA new task has been assigned to you.\n\nTASK TITLE: {taskTitle}\n\nTASK DESCRIPTION: {taskDescription}',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list = [useremail],
        fail_silently=False)

        if form.is_valid():
            form.save()
            return redirect('taskapp:index')
        else:
            print('form is not valid',form)
    else:
        form = TaskForm(request.GET or None)
    return render(request, 'taskapp/create_task.html',{'form': form})


@unauthenticated_user
def loginPage(request):
    if request.method=="POST":
        username = request.POST.get('username')
        password= request.POST.get('password')
        user = authenticate(request, username =username, password =password)

        if user is not None:
            login(request, user)
            return redirect('taskapp:index')
        else:
            messages.info(request,"Username or Password is Incorrect!!")

    context ={}
    return render(request, 'taskapp/login.html', context)


@login_required(login_url='taskapp:login')
@allowed_users(allowed_roles=['admin'])
def editTask(request,pk):
    task = Task.objects.get(pk=pk)
    if request.method == 'POST':
        form = TaskForm(request.POST, instance = task)
        datecreated = task.datecreated
        form.datecreated = datecreated

        useremail = request.POST.get('email')
        username = request.POST.get('name')
        taskTitle = request.POST.get('title')
        taskDescription = request.POST.get('description')
        
        send_mail(subject='Alloted Task Added with some Changes',
        message =f'NEW EMAIL FROM "COMPANY NAME".\n\nHello {username},\nYour Previous Task has been Edited and added with some new Content.\n\nTASK TITLE: {taskTitle}\n\nTASK DESCRIPTION: {taskDescription}',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list = [useremail],
        fail_silently=False)

        if form.is_valid():
            task = form.save()
            return redirect('taskapp:index')
        else:
            print('form is not valid',form)
    else:
        form = TaskForm(instance = task)
    return render(request, 'taskapp/create_task.html',{'form': form})


@login_required(login_url='taskapp:login')
@allowed_users(allowed_roles=['admin','user'])
def viewTask(request,pk):
    task = Task.objects.get(pk=pk)
    comments = Comments.objects.filter(task_id=pk)
    if request.method == 'POST':
        form = CommentsForm(request.POST)
        if form.is_valid():
            comment = form.save()
        else:
            print('form is not valid',form)
    else:
        form = CommentsForm(request.GET or None)
    return render(request, 'taskapp/view_task.html',{'task': task,'comments': comments,'form':form})

@login_required(login_url='taskapp:login')
@allowed_users(allowed_roles=['admin'])
def deleteTask(request, pk):
	delTask = Task.objects.get(link_id=pk)
	delTask.delete()
	return redirect('taskapp:index')

taskapp/templates/taskapp/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Task Roster</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
	<div class="container-fluid">
	{% block content %}
	{% endblock %}
    </div>
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

taskapp/templates/taskapp/index.html
<!DOCTYPE html>
<html>
    {% load static %}
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}{% endblock title %}</title>
        <meta name="description" content="Agro Admin - HTML5 Admin Template">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    
        <link rel="apple-touch-icon" href="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYybkhrYWVJbpmX8imVcThbQt2eNu7pwme8LpWr4YIOb0lVG8UQVJxEeMhBZSHj-MriaQ&usqp=CAU">
	    <link rel="shortcut icon" href="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYybkhrYWVJbpmX8imVcThbQt2eNu7pwme8LpWr4YIOb0lVG8UQVJxEeMhBZSHj-MriaQ&usqp=CAU">
    
        <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css"> -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
        <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css"> -->
        <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css"> -->
        <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.0/css/flag-icon.min.css"> -->
        <!-- <link rel="stylesheet" href="{% static 'assets/css/lib/datatable/dataTables.bootstrap.min.css' %}"> -->
        <!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js"></script> -->
        <!-- <link href="https://cdn.jsdelivr.net/npm/chartist@0.11.0/dist/chartist.min.css" rel="stylesheet"> -->
        <!-- <link href="https://cdn.jsdelivr.net/npm/jqvmap@1.5.1/dist/jqvmap.min.css" rel="stylesheet"> -->
    
        <!-- <link href="https://cdn.jsdelivr.net/npm/weathericons@2.1.0/css/weather-icons.css" rel="stylesheet" /> -->
        <link href="https://cdn.jsdelivr.net/npm/fullcalendar@3.9.0/dist/fullcalendar.min.css" rel="stylesheet" />
    
       <style>
        /* #weatherWidget .currentDesc {
            color: #ffffff!important;
        }
            .traffic-chart {
                min-height: 335px;
            }
            #flotPie1  {
                height: 150px;
            }
            #flotPie1 td {
                padding:3px;
            }
            #flotPie1 table {
                top: 20px!important;
                right: -10px!important;
            }
            .chart-container {
                display: table;
                min-width: 270px ;
                text-align: left;
                padding-top: 10px;
                padding-bottom: 10px;
            }
            #flotLine5  {
                 height: 105px;
            }
    
            #flotBarChart {
                height: 150px;
            }
            #cellPaiChart{
                height: 160px;
            }
            h3:nth-child(odd) {
            background: rgb(214, 207, 207);
            color:rgb(43, 111, 167);
            } */
            a:hover{
                text-decoration: none !important
            }
            .width-10{
                width: 10%
            }
            .width-55{
                width: 53.7%;
            }
            .width-20{
                width: 20%
            }
            th{
                color: white;
                margin: 0 20px
            }
            .task-completed{
                background-color:green !important;
            color: white;
            }
            .task-pending{
                background-color: #121212 !important;
            color: white;
            }
            .all-tasks{
                padding: 50px 0 0 50px;
                height: 91.2vh !important;
                background-image: url("https://th.bing.com/th/id/R.2dd87cc41532561a2a7c924a86ea4b18?rik=3k%2f47DYET4XrGw&riu=http%3a%2f%2fwallpaperping.com%2fwp-content%2fuploads%2f2019%2f05%2f586672285-landscape-background-images.jpg&ehk=dEdDQPHWuX5Hoq376nNQLNOjlvbhFGN54%2bOfrO2vu9s%3d&risl=1&pid=ImgRaw&r=0"), linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5));
                background-size: cover;
  background-blend-mode: overlay;
            }
</style>
    </head>
<body>
    {%  include 'taskapp/navbar.html' %}

    <div class="all-tasks">

        <table class="table table-striped table-inverse table-responsive">
            <thead class="thead-inverse">
                <tr>
                    <th class="width-10">View Task</th>
                    <th class="width-55">Task Title</th>
                    <th class="width-20">Task Created On</th>
                    <th class="width-20">Last Modified On</th>
                </tr>
                </thead>
                <tbody>
                {% for task in tasklist %}
                {% if task.name == 'Completed Task' or task.name == 'Task Completed' or task.name == 'completed task' or task.name == 'task completed' or task.name == 'done' or task.name == 'Done' %}
                <tr class="task-completed">
                    <td scope="row"><a  class="btn btn-primary"  href="{% url 'taskapp:viewTask' task.link_id %}">View Task </a></td>
                    <td>{{task.title}}</td>
                    <td>{{task.datecreated}}</td>
                    <td>{{task.datelastmodified}}</td>
                </tr>
                    {% else %}
    
                    <tr class="task-pending">
                        <td scope="row"><a  class="btn btn-primary"  href="{% url 'taskapp:viewTask' task.link_id %}">View Task </a></td>
                        <td>{{task.title}}</td>
                        <td>{{task.datecreated}}</td>
                        <td>{{task.datelastmodified}}</td>
                    </tr>
                 {% endif %}
                 {% endfor %}
                </tbody>
        </table>
    </div>
</body>
</html>

taskapp/templates/taskapp/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<link rel="apple-touch-icon" href="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYybkhrYWVJbpmX8imVcThbQt2eNu7pwme8LpWr4YIOb0lVG8UQVJxEeMhBZSHj-MriaQ&usqp=CAU">
	<link rel="shortcut icon" href="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYybkhrYWVJbpmX8imVcThbQt2eNu7pwme8LpWr4YIOb0lVG8UQVJxEeMhBZSHj-MriaQ&usqp=CAU">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

                {% for message in messages %}
                    <p id="messages">{{message}}</p>
                {% endfor %}
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'taskapp:register' %}" class="ml-2">Sign Up</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>

</html>

taskapp/templates/taskapp/navbar.html
{% load static %}


<style>
    .hello-msg{
      font-size: 18px;
      color: #fff;
      margin-right: 20px;
    }

    .nav-link{
      color: white !important
    }
    {% if request.user.is_staff %}
    .margin-880{
      margin-left: 800px;
    }
    {% else %}
    .margin-880{
      margin-left: 925px;
    }
    {% endif %}
    .navbar-brand{
      color: white !important
    }
</style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'taskapp:index' %}">Task Roaster</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"  
      aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavId">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      {% if request.user.is_staff %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'taskapp:createTask' %}">Create New Task <span class="sr-only">(current)</span></a>
      </li>
      {% endif %}
      <li class="nav-item margin-880">
        <a class="nav-link">Hello, {{request.user}}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'taskapp:logout' %}">Logout</a>
      </li>
    </ul>
  </div>
</nav>

taskapp/templates/taskapp/view_task.html
<!DOCTYPE html>
<html>
    {% load static %}
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}{% endblock title %}</title>
        <meta name="description" content="CodersArts">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    
        <link rel="apple-touch-icon" href="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYybkhrYWVJbpmX8imVcThbQt2eNu7pwme8LpWr4YIOb0lVG8UQVJxEeMhBZSHj-MriaQ&usqp=CAU">
	    <link rel="shortcut icon" href="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYybkhrYWVJbpmX8imVcThbQt2eNu7pwme8LpWr4YIOb0lVG8UQVJxEeMhBZSHj-MriaQ&usqp=CAU">
    
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.0/css/flag-icon.min.css">
        <link rel="stylesheet" href="{% static 'assets/css/cs-skin-elastic.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/lib/datatable/dataTables.bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
        <!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js"></script> -->
        <link href="https://cdn.jsdelivr.net/npm/chartist@0.11.0/dist/chartist.min.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/jqvmap@1.5.1/dist/jqvmap.min.css" rel="stylesheet">
    
        <link href="https://cdn.jsdelivr.net/npm/weathericons@2.1.0/css/weather-icons.css" rel="stylesheet" />
        <link href="https://cdn.jsdelivr.net/npm/fullcalendar@3.9.0/dist/fullcalendar.min.css" rel="stylesheet" />
    
       <style>
        
            .content{
                margin: 0 20%;
            }
            .btn {
                margin:5px;
            }

            .btn-primary{
                float:right;
            }
            .spacer{
                margin-bottom: 5px
            }
      </style>
    </head>
<body>
    {%  include 'taskapp/navbar.html' %}
    <a  class="btn btn-warning"  href="{% url 'taskapp:index' %}">Back </a>
    <a class="btn btn-danger"  href="{% url 'taskapp:deleteTask' task.link_id %}">Delete This Task</a>
    <a class="btn btn-primary"  href="{% url 'taskapp:editTask' task.link_id %}">Edit This Task</a>
    <div class= "content"> 
        <div class="row spacer">
        <div class="col-3">
            {% if task.name == 'Completed Task' or task.name == 'Task Completed' or task.name == 'completed task' or task.name == 'task completed' or task.name == 'done' or task.name == 'Done' %}
            <label>Task Status</label>
            {% else %}
            <label>Assigned to</label>
            {% endif %}
        </div>
        <div class="col-7">
            <div class="input-group">
                {{task.name}}
            </div>
        </div>
    </div>
    <div class="row spacer">
        <div class="col-3">
            <label>Email</label>
        </div>
        <div class="col-7">
            <div class="input-group">
                {{task.email}}
            </div>
        </div>
    </div>
    <div class="row spacer">
        <div class="col-3">
            <label>Title</label>
        </div>
        <div class="col-7">
            <div class="input-group">
                {{task.title}}
            </div>
        </div>
    </div>
    <div class="row spacer">
        <div class="col-3">
            <label>Description</label>
        </div>
        <div class="col-7">
            <div class="input-group">
                {{task.description}}
            </div>
        </div>
    </div>
    <div class="row spacer">
        <div class="col-3">
            <label>Created Date</label>
        </div>
        <div class="col-7">
            <div class="input-group">
                {{task.datecreated}}
            </div>
        </div>
    </div>
    <div class="row spacer">
        <div class="col-3">
            <label>Modified Date</label>
        </div>
        <div class="col-7">
            <div class="input-group">
                {{task.datelastmodified}}
            </div>
        </div>
    </div>
<hr/>
    <div class="row spacer" style="background: grey; color:white;">
        <div class="col-9">
            <label>Comments Below</label>
        </div>
        {% for i in comments %}
        <div class="col-9">
            <div class="input-group">
              {{forloop.counter}}.  {{i}}
            </div>
        </div>
        {% endfor %}
    </div>
    <br>
    <form class="form-horizontal" method="POST">
        {% csrf_token %}
        <div class="row spacer">
            <div class="col-2">
                <label>{{form.task.label}}</label>
            </div>
            <div class="col-7">
                <div class="input-group">
                    {{form.task}}
                </div>
            </div>
        </div>
        <div class="row spacer">
            <div class="col-2">
                <label>{{form.comment.label}}</label>
            </div>
            <div class="col-7">
                <div class="input-group">
                    {{form.comment}}
                </div>
            </div>
        </div>
    <div class="row spacer">
        <div class="col-4 offset-2">
            <button type="submit" class="btn btn-block btn-primary">Add Comment</button>
        </div>
    </div>
</form>
</div>


</body>
</html>